version: '3'
services:
  pluto_db:
    image: postgres:9.6-alpine
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    ports:
      - 6543:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=pluto
      - POSTGRES_DB=pluto

  pluto_dev_dbloader:
    build:
      context: .
      dockerfile: ./dev_container/dev.Dockerfile
    image: pluto_dev:latest
    volumes:
      - .:/code
      - /code/node_modules
    command: ./database/dbloader/run_importer_in_docker.sh
  pluto_nginx:
    image: nginx:stable-alpine
    volumes:
      - ./test_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9001:8001
      - 9002:8002
      - 9003:8003
      - 9004:8004

  pluto_s3server:
    image: scality/s3server
    ports:
      - 8000:8000
    volumes:
      - s3-data-dev:/usr/src/app/localData
      - s3-meta-dev:/usr/src/app/localMetadata

volumes:
  pgdata-dev:
  s3-data-dev:
  s3-meta-dev:

