filebeat.prospectors:
  - type: log
    # Watch all docker logs on this node
    paths:
      - '/var/lib/docker/containers/*/*.log'
    json.message_key: log
    json.keys_under_root: true
    # Don't watch files that were created > 10 minutes ago (ie old containers not currently running)
    ignore_older: 10m
    
    # Combine multiline log files if the message starts with 2 or more spaces (stacktraces)
    multiline.pattern: '^  '
    multiline.negate: false
    multiline.match: after

    processors:
      # Add docker information like container name
      - add_docker_metadata: ~
      # Skip logs coming from the EBK stack
      - drop_event:
          when:
            or:
              - contains:
                  docker.container.name: metricbeat
              - contains:
                  docker.container.name: filebeat
              - contains:
                  docker.container.name: kibana
              - contains:
                  docker.container.name: elasticsearch

setup.kibana:
  host: "${KIBANA_HOST}"

# Debugging purposes - log to stdout
# output.console:
#   pretty: true

output.elasticsearch:
  hosts: ["${ELASTIC_HOST}"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  pipelines:
    - pipeline: http
      when.contains:
        docker.container.name: node-example
