const ParserRuleAPI = require('./ParserRuleAPI');

/**
 * This API class is used to describe the interface to rule operations. This base class can be used by rules that
 * interact with operators.
 */
class TableRuleAPI extends ParserRuleAPI {

    /**
     * The base constructor. This simply sets <code>this.config</code> to the passed in configuration object. This config object
     * will be the rule's individual configuration (if any) and additionally contain <code>RootDirectory</code> which defaults to
     * the application's root directory if not set, <code>TempDirectory</code> which defaults to the application's temporary
     * directory if not set, <code>OutputEncoding</code> which is set to the rule's Encoding if set or to the ruleset's Encoding
     * if set, and <code>utf8</code> if none are set, and <code>Encoding</code> which is set to the input file's encoding. (Note
     * the distinction between <code>Encoding</code> and <code>OutputEncoding</code>. <code>Encoding</code> is set to the source file's encoding and
     * <code>OutputEncoding</code> is set to the encoding of the file generated by the rule. In general these would be the same
     * but rule's may want to switch one uncommon encoding for another more common one.)
     * @param localConfig {object} the rule's configuration as defined in the ruleset file or a standalone config file.
     */
    constructor(localConfig) {
        super(localConfig);
    }

    /**
     * Derived classes should override this method if they need to do anything before the processing of the data starts.
     * <br/>Note that rules that use streams and modify the metadata, because of their asynchronous nature, should do so
     * in a <code>start()</code> method. Modifying the metdata any later could mean that the changes are not
     * applied until after the next rule needs the changes. However rules that use data objects or files are safe
     * to modify metadata at any point, in the <code>start()</code> or <code>finish()</code> methods since these
     * rules would run synchronously.
     * @param tableParser {TableParserAPI} the parser for this rule
     */
    start(tableParser) {
        // Do any pre-processing.
    }

    /**
     * Derived classes should override this method if they need to do anything after the processing of records is complete.
     * @see {@link CSVRuleAPI#start|start}
     */
    finish() {
        // Do any post-processing.
    }

    /**
     * Derived classes should implement this method to process individual records.
     * @param record {array} one record from the csv file.
     * @param rowId {object | number} row indicator, usually the row number
     * @returns {array} a record, either the original one if no modifications were carried out or a new one.
     */
    processRecord(record, rowId) {
        // Process the record and return the new record.
        return record;
    }

    /**
     * Derived classes can implement this method to return true if they need the header rows
     * @returns {boolean} true if header rows should be passed to the processRecord method
     */
    get processHeaderRows() {
        return false;
    }

    static get Type() {
        return "table_rule";
    }

    static get Parser() {
        return "table_parser";
    }


    /**
     * Given the value of a property this validates whether the given value is a column label or column number
     * and if so returns the column number otherwise an error is posted to the log and <code>undefined</code> is
     * returned.
     * @param {string} propertyValue the value of a config column property. If this is <code>undefined</code> then
     * <code>this.config.column</code> is used.
     * @param {string} propertyName the name of the property - used in error messages. Defaults to 'column' if not set.
     * @returns {number|undefined} the column number represented by the propertyValue or undefined if the value is not valid.
     */
    getValidatedColumnProperty(propertyValue, propertyName) {
        propertyValue = propertyValue == undefined ? this.config.column : propertyValue;
        propertyName = propertyName == undefined ? 'column' : propertyName;

        var result = undefined;
        if (propertyValue === undefined)
            this.error(`Configured without a '${propertyName}' property.`);
        else if (isNaN(propertyValue)) {
            let sharedData = this.config.sharedData;
            if (sharedData && sharedData.columnLabels) {
                let columnLabels = sharedData.columnLabels;
                if (columnLabels.length == undefined) {
                    this.error(`Shared 'columnLabels' is not an array.`);
                    return result;
                }
                else if (columnLabels.length == 0) {
                    this.error(`Shared 'columnLabels' has no content.`);
                    return result;
                }

                // Found a column label not index.
                let index = columnLabels.indexOf(propertyValue);
                if (index < 0)
                    this.error(`Configured with a column label '${propertyValue}' that is not in sharedData.columnLabels.`);
                else
                    result = index;
            }
            else
                this.error(`Configured with a non-number '${propertyName}'. Got '${propertyValue}'.`);
        }
        else if (propertyValue < 0)
            this.error(`Configured with a negative '${propertyName}'. Got '${propertyValue}'.`);
        else {
            result = Math.floor(parseFloat(propertyValue));
            if (!Number.isInteger(parseFloat(propertyValue)))
                this.warning(`Configured with a non-integer '${propertyName}'. Got '${propertyValue}', using ${result}.`);
        }
        return result;
    }
}

module.exports = TableRuleAPI;	// Export this so derived classes can extend it.

