metricbeat.modules:
- module: docker
  # metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  metricsets: ["cpu", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 30s
- module: system
  metricsets:
    - cpu
    - memory
    - network
  enabled: true
  period: 30s
  cpu_ticks: false

setup.kibana:
   host: "http://kibana:5601"

setup.dashboards:
  enabled: true

# Debugging purposes - log to stdout
# output.console:
#   pretty: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
